# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make buildDeps
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - binary: minikube-support
    id: minikube-support
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    ldflags:
      - -X 'github.com/qaware/minikube-support/version.Version={{.Version}}'
      - -X 'github.com/qaware/minikube-support/version.Revision={{.ShortCommit}}'
      - -X 'github.com/qaware/minikube-support/version.Branch={{.Branch}}'
      - -X 'github.com/qaware/minikube-support/version.CommitDate={{.CommitTimestamp}}'
      - -s -w -extldflags '-static'
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
  - binary: minikube-support
    id: minikube-support-macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    ldflags:
      - -X 'github.com/qaware/minikube-support/version.Version={{.Version}}'
      - -X 'github.com/qaware/minikube-support/version.Revision={{.ShortCommit}}'
      - -X 'github.com/qaware/minikube-support/version.Branch={{.Branch}}'
      - -X 'github.com/qaware/minikube-support/version.CommitDate={{.CommitTimestamp}}'
      - -s -w -extldflags '-static'
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
#    hooks:
#      post: gon gon.hcl
archives:
checksum:
  name_template: 'checksums.txt'
  algorithm: sha512
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
