language: go
go:
  - "1.13.x"
os:
  - linux
  - osx
addons:
  sonarcloud:
    organization: "chr-fritz"

before_install:
  - make buildDeps pb generate
git:
  depth: false

jobs:
  allow_failures:
    - os: linux

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - make ci
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  # SonarQube analysis will only run on macOS as it is already fully implemented.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sonar-scanner; fi

