apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          image: nginx:1.19
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: demo
      protocol: TCP
      targetPort: http
  selector:
    app: demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  defaultBackend:
    service:
      name: demo
      port:
        name: http
  rules:
    - host: demo.minikube
  tls:
    - secretName: demo
      hosts:
        - demo.minikube
