name: GoBuild
on: [push]
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
      fail-fast: false
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install buildDeps
        run: |
          export PATH=$HOME/go/bin:$PATH
          make buildDeps

      - name: Build
        run: |
          export PATH=$HOME/go/bin:$PATH
          make generate test build
