name: Go-Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
      fail-fast: false
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install buildDeps and generate sources
        run: |
          export PATH=$HOME/go/bin:$PATH
          make buildDeps generate

      - name: Run Tests
        run: |
          export PATH=$GOPATH/bin:$HOME/go/bin:$PATH
          make test

      - name: Build Artifacts
        run: goreleaser build --rm-dist --snapshot
