name: Go-Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
        -   name: Set up Go 1.16
            uses: actions/setup-go@v1
            with:
                go-version: 1.16
            id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Install buildDeps and generate sources
        run: |
          export PATH=$HOME/go/bin:$PATH
          make buildDeps generate

      - name: Run Tests
        run: |
          export PATH=$GOPATH/bin:$HOME/go/bin:$PATH
          timeout 10m make test
